

--USE TENNIS;

CREATE TABLE JOUEUR(
ID NUMBER GENERATED ALWAYS AS IDENTITY,
NOM VARCHAR(20) NOT NULL,
PRENOM VARCHAR(20),
SEXE CHAR(1) NOT NULL,/*H, F*/
PRIMARY KEY(ID)
);


CREATE TABLE TOURNOI(
ID NUMBER GENERATED ALWAYS AS IDENTITY,
NOM VARCHAR(20) NOT NULL,
CODE VARCHAR(2) NOT NULL,
PRIMARY KEY(ID)
);


CREATE TABLE EPREUVE(
ID NUMBER GENERATED ALWAYS AS IDENTITY,
ANNEE SMALLINT NOT NULL,
TYPE_EPREUVE CHAR(1) NOT NULL,/*H, F*/
ID_TOURNOI NUMBER(6) NOT NULL,
PRIMARY KEY(ID),
FOREIGN KEY(ID_TOURNOI) REFERENCES TOURNOI(ID)
);


CREATE TABLE MATCH_TENNIS(
ID NUMBER GENERATED ALWAYS AS IDENTITY,
ID_EPREUVE NUMBER(6) NOT NULL,
ID_VAINQUEUR NUMBER(6) NOT NULL,
ID_FINALISTE NUMBER(6) NOT NULL,
PRIMARY KEY(ID),
FOREIGN KEY(ID_VAINQUEUR) REFERENCES JOUEUR(ID),
FOREIGN KEY(ID_FINALISTE) REFERENCES JOUEUR(ID),
FOREIGN KEY(ID_EPREUVE) REFERENCES EPREUVE(ID)
);

CREATE TABLE SCORE_VAINQUEUR(
ID NUMBER GENERATED ALWAYS AS IDENTITY,
ID_MATCH NUMBER(6) NOT NULL,
SET_1 NUMBER(2) NULL,/*normalement NOT NULL sauf si abandon*/
SET_2 NUMBER(2) NULL,/*normalement NOT NULL sauf si abandon*/
SET_3 NUMBER(2) NULL,
SET_4 NUMBER(2) NULL,
SET_5 NUMBER(2) NULL,
PRIMARY KEY(ID),
FOREIGN KEY(ID_MATCH) REFERENCES MATCH_TENNIS(ID)
);